### ISSUE TITLE
It's broken

### ISSUE THREAD

**Issue by RyanCCollins** [mikaelm1/Swifty-Chess#3]
I can't get this to compile on my TI-84.  It's broken!

😖 

![image](https://cloud.githubusercontent.com/assets/13810084/20251108/79f77ea8-a9e4-11e6-89e5-ab6c8ca32f76.png)

**Comment by mikaelm1** [comment]
What error are you getting when you try to compile?

**Comment by RyanCCollins** [comment]
👨 👨 👨 
💩 💩 💩 
〰️ 〰️ 〰️ 
🚽 🚽 🚽

**Comment by mikaelm1** [comment]
Hmm...That looks like it could be related to the version number. Are you compiling with Swift 3? That's the only version the app works with.

**Comment by RyanCCollins** [comment]
❤️  🗡

**Comment by mikaelm1** [comment]
Great! Glad we were able to fix it.
