### ISSUE TITLE
 Is it possible to make game via server?

### ISSUE THREAD

**Issue by aitemr** [mikaelm1/Swifty-Chess#6]

**Comment by mikaelm1** [comment]
@aitemr Thanks for checking out the project. Yes it is possible to make a multiplayer version of this and in fact, that is what I am currently doing. I'll be releasing the multiplayer version to the App store soon, but as of now, I'm not planning on making it open source.

**Comment by aitemr** [comment]
@mikaelm1 Hi! How are you? Did you release multiplayer version to the App store?

**Comment by mikaelm1** [comment]
@aitemr Hey! Yes I've released the app. Here's the link: https://itunes.apple.com/us/app/chess-clans/id1214644602

**Comment by aitemr** [comment]
@mikaelm1 Any plans to update this repo?

**Comment by mikaelm1** [comment]
I don't think I'll have the time for it any time soon. But there is an open source chess library written in Swift by @nvzqz that I would recommend: https://github.com/nvzqz/Sage
